'use client';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {useEffect,useState,useRef} from 'react';
import {api} from '../../client';
import {useLocale} from '../../i18n';
import {Library} from '../../library';
import {TrophyMark} from '../../components';
type Player={handle:string;display_name:string;relationship:string;request_id:string|null;viewer_authenticated:boolean;library_visible?:boolean};
type Trophy={trophy_id:string;grade:string;hidden:boolean;name:string;description:string|null;icon_url:string|null;mine:boolean|null;friend:boolean|null;mine_present:boolean;friend_present:boolean};
type Game={source:string;title_id:string;title:string;artwork_url:string|null;total:number;mine_earned:number;friend_earned:number;trophies:Trophy[]};
type Comparison={friend:{handle:string;display_name:string};games:Game[]};
export default function PlayerPage(){
 const params=useParams<{handle:string}>();const handle=params.handle;
 const {t,preferences,ready:localeReady}=useLocale();
 const [player,setPlayer]=useState<Player|null>(null),[comparison,setComparison]=useState<Comparison|null>(null),[detail,setDetail]=useState<Game|null>(null);
 const selectionVersion=useRef(0);const selectedRef=useRef('');
 const [selected,setSelected]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 async function refresh(){const p=await api('/players/'+encodeURIComponent(handle));setPlayer(p);if(p.relationship==='friends'){setComparison(await api('/account/friends/'+handle+'/compare?language='+encodeURIComponent(preferences)));if(selectedRef.current){const version=selectionVersion.current;const [source,title]=selectedRef.current.split('|');const data=await api('/account/friends/'+handle+'/compare?language='+encodeURIComponent(preferences)+'&source='+encodeURIComponent(source)+'&title_id='+encodeURIComponent(title));if(version===selectionVersion.current)setDetail(data.games[0]||null);}}else{selectionVersion.current++;setComparison(null);setDetail(null);setSelected('');selectedRef.current='';}}
 useEffect(()=>{if(!localeReady)return;refresh().catch(e=>{setError(e.message);setComparison(null);setDetail(null);}).finally(()=>setReady(true));const timer=setInterval(()=>refresh().catch(()=>{setComparison(null);setDetail(null);}),30000);return()=>clearInterval(timer);},[handle,preferences,localeReady]);
 async function act(action:string){if(!player)return;setBusy(true);setError('');try{if(action==='request')await api('/account/friends/request',{handle:player.handle});else await api('/account/friends/'+player.request_id,{action});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function choose(value:string){const version=++selectionVersion.current;setSelected(value);selectedRef.current=value;setFilter('all');setDetail(null);setError('');if(!value)return;setBusy(true);try{const [source,title]=value.split('|');const data:Comparison=await api('/account/friends/'+handle+'/compare?language='+encodeURIComponent(preferences)+'&source='+encodeURIComponent(source)+'&title_id='+encodeURIComponent(title));if(version===selectionVersion.current)setDetail(data.games[0]||null);}catch(e){if(version===selectionVersion.current)setError((e as Error).message);}finally{if(version===selectionVersion.current)setBusy(false);}}
 useEffect(()=>{if(player)document.title=player.display_name+' · TrophySync';},[player]);
 function state(earned:boolean|null,present:boolean){return !present?t('Not imported'):earned===true?t('Earned'):earned===false?t('Locked'):t('Unknown');}
 if(!ready)return <p role="status">{t('Loading profile…')}</p>;
 if(!player)return <section className="social-panel"><h1>{t('Player not found')}</h1>{error&&<p role="alert">{error}</p>}<Link href="/friends">{t('Find a player')}</Link></section>;
 const games=comparison?.games||[];const shown=(detail?.trophies||[]).filter(row=>filter==='all'||filter==='mine'&&row.mine===true&&row.friend!==true||filter==='friend'&&row.friend===true&&row.mine!==true||filter==='both'&&row.mine===true&&row.friend===true);
 return <><Link className="back-link" href={player.relationship==='self'?'/':'/friends'}>← {t(player.relationship==='self'?'My library':'Friends')}</Link><section className="public-profile social-panel"><span className="person-avatar" aria-hidden="true">{player.display_name.slice(0,1)}</span><div><p className="eyebrow">{t('TrophySync profile')}</p><h1>{player.display_name}</h1><p className="subtle">@{player.handle}</p></div><div className="profile-actions">
 {player.relationship==='self'?<Link className="button" href="/friends">{t('Edit profile')}</Link>:!player.viewer_authenticated?<Link className="button" href="/login">{t('Sign in to send a request')}</Link>:player.relationship==='friends'?<><span className="earned-badge is-earned">{t('Friends')}</span><button className="secondary" disabled={busy} onClick={()=>act('remove')}>{t('Remove friend')}</button></>:player.relationship==='outgoing'?<><span>{t('Request sent')}</span><button className="secondary" disabled={busy} onClick={()=>act('cancel')}>{t('Cancel request')}</button></>:player.relationship==='incoming'?<><button disabled={busy} onClick={()=>act('accept')}>{t('Accept')}</button><button className="secondary" disabled={busy} onClick={()=>act('deny')}>{t('Deny')}</button></>:<button disabled={busy} onClick={()=>act('request')}>{t('Send friend request')}</button>}
 </div></section>{error&&<p className="error" role="alert">{error}</p>}
 {!player.library_visible&&player.relationship!=='friends'&&player.relationship!=='self'&&<p className="social-panel subtle">{t('Trophy comparisons are available after both players approve the friendship.')}</p>}
 {(player.relationship==='self'||player.library_visible)&&<Library embedded playerHandle={player.relationship==='self'?undefined:handle}/>}
 {comparison&&<section><div className="page-heading"><div><h2>{t('Compare trophies')}</h2><p className="subtle">{t('Secret trophies stay hidden until you earn them.')}</p></div></div><div className="compare-totals"><div><span>{t('You')}</span><strong>{games.reduce((n,g)=>n+g.mine_earned,0)} {t('earned trophies')}</strong></div><div><span>{player.display_name}</span><strong>{games.reduce((n,g)=>n+g.friend_earned,0)} {t('earned trophies')}</strong></div></div>
 <div className="compare-toolbar"><label>{t('Compare game')}<select aria-label={t('Compare game')} value={selected} disabled={busy} onChange={e=>choose(e.target.value)}><option value="">{t('All games')}</option>{games.map(g=><option key={g.source+'|'+g.title_id} value={g.source+'|'+g.title_id}>{g.title} ({g.source==='ps5_native'?'PS5':'PS4'})</option>)}</select></label>{selected&&<label>{t('Show comparison')}<select aria-label={t('Show comparison')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('All trophies')}</option><option value="mine">{t('Only you earned')}</option><option value="friend">{t('Only your friend earned')}</option><option value="both">{t('Both earned')}</option></select></label>}</div>
 {busy&&<p role="status">{t('Loading comparison…')}</p>}
 {!selected?<div className="comparison-games">{games.map(g=><button className="comparison-game" key={g.source+'|'+g.title_id} onClick={()=>choose(g.source+'|'+g.title_id)}>{g.artwork_url?<img src={g.artwork_url} alt=""/>:<span className="comparison-art"><TrophyMark/></span>}<span><strong>{g.title}</strong><small>{g.source==='ps5_native'?'PS5':'PS4'}</small></span><span className="comparison-score"><span>{t('You')}: {g.mine_earned}/{g.total}</span><span>{player.display_name}: {g.friend_earned}/{g.total}</span></span><span aria-hidden="true">→</span></button>)}{!games.length&&<p>{t('No recorded trophies to compare yet.')}</p>}</div>:detail&&<section className="social-panel"><h2>{detail.title}</h2><ul className="comparison-trophies">{shown.map(row=><li key={row.trophy_id} className={row.mine===true?'earned':''}><div className="comparison-icon">{row.icon_url?<img src={row.icon_url} alt=""/>:<span aria-label={t('Trophy artwork hidden until earned')}>🔒</span>}</div><div className="comparison-description"><span className={'trophy-grade '+row.grade}><TrophyMark/>{t(row.grade?row.grade[0].toUpperCase()+row.grade.slice(1):'Unknown')}</span><h3>{row.hidden?t('Hidden trophy'):row.name}</h3><p>{row.hidden?t('Earn this trophy to reveal its name and description.'):row.description}</p></div><div className="comparison-status"><span>{t('You')} <strong className={'earned-badge '+(row.mine===true?'is-earned':'is-locked')}>{state(row.mine,row.mine_present)}</strong></span><span>{player.display_name} <strong className={'earned-badge '+(row.friend===true?'is-earned':'is-locked')}>{state(row.friend,row.friend_present)}</strong></span></div></li>)}</ul>{!shown.length&&<p>{t('No trophies match this filter.')}</p>}</section>}
 </section>}</>;
}
